<a href="https://colab.research.google.com/github/IqmanS/Machine-Learning-Notebooks/blob/main/course_assignments/ML_Assignment_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Iqman Singh Bhatia
## 102103189

In [ ]:
#Q1 a
import numpy as np
arr = np.array([1,2,3,6,5,4])
print(arr)
new_arr = arr[::-1]
print(new_arr)

[1 2 3 6 5 4]
[4 5 6 3 2 1]


In [ ]:
# Q1 b
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(array1)
new_array1 = np.ndarray.flatten(array1)
print(new_array1)

[[1 2 3]
 [2 4 5]
 [1 2 3]]
[1 2 3 2 4 5 1 2 3]


In [ ]:
#Q1 c
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print("arr1 ", arr1)
print("arr2 ", arr2)
print("arr1 > arr2")
print(np.greater(arr1,arr2))
print("arr1 >= arr2")
print(np.greater_equal(arr1,arr2))
print("arr1 < arr2")
print(np.less(arr1,arr2))
print("arr1 <= arr2")
print(np.less_equal(arr1,arr2))
print("arr1 = arr2")
print(np.equal(arr1,arr2))



arr1  [[1 2]
 [3 4]]
arr2  [[1 2]
 [3 4]]
arr1 > arr2
[[False False]
 [False False]]
arr1 >= arr2
[[ True  True]
 [ True  True]]
arr1 < arr2
[[False False]
 [False False]]
arr1 <= arr2
[[ True  True]
 [ True  True]]
arr1 = arr2
[[ True  True]
 [ True  True]]


In [ ]:
#Q1 d
x = np.array([1,2,3,4,5,1,2,1,1,1])
print(x)
print("most frequent value is ", np.bincount(x).argmax())
print("Index values are ", np.where(x==1)[0])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
print(y)
print("most frequent value is ", np.bincount(x).argmax())
print("Index values are ", np.where(y==1)[0])


[1 2 3 4 5 1 2 1 1 1]
most frequent value is  1
Index values are  [0 5 7 8 9]
[1 1 1 2 3 4 2 4 3 3]
most frequent value is  1
Index values are  [0 1 2]


In [ ]:
# Q1 e
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
arr_gfg = np.array(gfg)
print(gfg)
sum = np.sum(gfg)
print("Sum of elements is ", sum)
a = np.sum(arr_gfg,axis=0)
print("Sum of elememts column wise ",a)
b = np.sum(arr_gfg, axis=1)
print("Sum of elements row wise ",b)


[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
Sum of elements is  45
Sum of elememts column wise  [20  9 16]
Sum of elements row wise  [14 16 15]


In [ ]:
# Q1 f

n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])


diagonal_sum = np.trace(n_array)
print("Sum of diagonal elements:", diagonal_sum)

eigenvalues = np.linalg.eigvals(n_array)
print("Eigenvalues of matrix:")
print(eigenvalues)

eigenvectors = np.linalg.eig(n_array)
print("Eigenvectors of matrix:")
print(eigenvectors)

inverse_matrix = np.linalg.inv(n_array)
print("Inverse of matrix:")
print(inverse_matrix)

determinant = np.linalg.det(n_array)
print("Determinant of matrix:", determinant)


Sum of diagonal elements: 176
Eigenvalues of matrix:
[98.16835147 28.097044   49.73460452]
Eigenvectors of matrix:
(array([98.16835147, 28.097044  , 49.73460452]), array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))
Inverse of matrix:
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix: 137180.0000000001


In [ ]:
# Q1 g
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
result = np.dot(p, q)
covariance = np.cov(p, q)
print("Matrix Multiplication Result:")
print(result)
print("Covariance between Matrices:")
print(covariance)


Matrix Multiplication Result:
[[16 19]
 [26 31]]
Covariance between Matrices:
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
#Q1 h
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner = np.inner(x,y)
print("Inner product is ", inner)
outer = np.outer(x,y)
print("Outer product is ", outer)
X, Y = np.meshgrid(x.flatten(), y.flatten())
cartesian_product = np.column_stack((X.ravel(), Y.ravel()))
print("Cartesian Product:")
print(cartesian_product)

Inner product is  [[17 52]
 [13 62]]
Outer product is  [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian Product:
[[ 2  1]
 [ 3  1]
 [ 4  1]
 [ 3  1]
 [ 2  1]
 [ 9  1]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2  0]
 [ 3  0]
 [ 4  0]
 [ 3  0]
 [ 2  0]
 [ 9  0]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2 10]
 [ 3 10]
 [ 4 10]
 [ 3 10]
 [ 2 10]
 [ 9 10]
 [ 2  3]
 [ 3  3]
 [ 4  3]
 [ 3  3]
 [ 2  3]
 [ 9  3]]


In [ ]:
# Q2 a
array = np.array([[1, -2, 3],[-4, 5, -6]])
print(array)
new = np.fabs(array)
print(new)
flat_arr = np.ndarray.flatten(array)
print(flat_arr)
print("25th percentile of flattened array : ",np.percentile(flat_arr,25))
print("50th percentile of flattened array : ",np.percentile(flat_arr,50))
print("75th percentile of flattened array : ",np.percentile(flat_arr,75))
print("Percentiles for each column :",np.percentile(array,[25,50,75],axis=0))
print("Percentiles for each row :",np.percentile(array,[25,50,75],axis=1))

[[ 1 -2  3]
 [-4  5 -6]]
[[1. 2. 3.]
 [4. 5. 6.]]
[ 1 -2  3 -4  5 -6]
25th percentile of flattened array :  -3.5
50th percentile of flattened array :  -0.5
75th percentile of flattened array :  2.5
Percentiles for each column : [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles for each row : [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [ ]:
#Q2 b
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print(a)
print("Floor values : ", np.floor(a))
print("Ceiling values : ", np.ceil(a))
print("Truncated values : ", np.trunc(a))
print("Rounded values : ", np.round(a))


[-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]
Floor values :  [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values :  [-1. -1. -0.  1.  2.  2.  3.]
Truncated values :  [-1. -1. -0.  0.  1.  1.  3.]
Rounded values :  [-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
# Q3 a
array = np.array([10, 52, 62, 16, 16, 54, 453])
print(array)
print("Sorted array : ", np.sort(array))
print("Indices of sorted array : ", np.argsort(array))
k = 4
print("4 smallest values : ", np.sort(array[:k]))
n = 5
print("5 largest values : ", np.sort(array[-n :]))


[ 10  52  62  16  16  54 453]
Sorted array :  [ 10  16  16  52  54  62 453]
Indices of sorted array :  [0 3 4 1 5 2 6]
4 smallest values :  [10 16 52 62]
5 largest values :  [ 16  16  54  62 453]


In [ ]:
# Q3 b
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print(array)
print("Integer elements are : ", array[array.astype(int)==array])
print("Float elements are : ", array[array.astype(float)==array])

[1.  1.2 2.2 2.  3.  2. ]
Integer elements are :  [1. 2. 3. 2.]
Float elements are :  [1.  1.2 2.2 2.  3.  2. ]


In [ ]:
#Q4
from PIL import Image


def img_to_array(path, output_path):
    image = Image.open(path)

    image_array = np.array(image)

    with open(output_path, 'w') as file:
        for row in image_array:
            for pixel in row:
                file.write(' '.join(map(str, pixel)) + '\n')

img_path = '/content/2017-02-17.png'
output_path = 'output_array.txt'
img_to_array(img_path, output_path)


FileNotFoundError: ignored