<a href="https://colab.research.google.com/github/IqmanS/ai_ml/blob/main/numpy_notebook/Numpy_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#Generating Data

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.random()

0.6054466240255939

In [ ]:
np.random.random((2,3))

array([[0.39422371, 0.92504253, 0.0281926 ],
       [0.20116776, 0.37389416, 0.75977426]])

In [ ]:
np.random.randn(2,3)

array([[ 0.97563989, -1.53857726, -1.2131896 ],
       [ 0.61917042,  1.28054935, -0.46649576]])

In [ ]:
arr = np.random.randn(10000)
arr

array([-1.27355037, -1.57385272, -0.4564705 , ..., -0.92440843,
       -0.60802795, -0.26136688])

In [ ]:
arr.mean()

-0.005238816841062459

In [ ]:
arr.var()

1.01137166535855

In [ ]:
arr.std()

1.0056697595923574

In [ ]:
m = np.random.randn(10000,3)
m

array([[ 0.80501452,  0.23350572, -0.86698643],
       [-0.1207563 , -1.31766077,  0.93961716],
       [ 0.31696346,  1.17352919,  1.02409071],
       ...,
       [ 0.16785901,  0.62348315, -0.33428298],
       [ 0.28759178,  0.2606601 , -1.8745823 ],
       [-0.11991858, -2.4278585 , -1.72575141]])

In [ ]:
m.mean(axis=0)    #mean of all columns

array([-0.00762542,  0.01837989, -0.00057625])

In [ ]:
m.mean(axis=1)    #mean of all rows


array([ 0.05717794, -0.16626663,  0.83819445, ...,  0.15235306,
       -0.44211014, -1.4245095 ])

In [ ]:
m.mean(axis=1).shape

(10000,)

In [ ]:
np.cov(m)           #covariance 

array([[ 0.72221541, -0.59550344, -0.25123273, ...,  0.27220046,
         0.99672772,  0.53854978],
       [-0.59550344,  1.27537931, -0.1021221 , ..., -0.53995683,
        -1.18005215,  0.44074198],
       [-0.25123273, -0.1021221 ,  0.20934428, ...,  0.02972014,
        -0.20548559, -0.53622537],
       ...,
       [ 0.27220046, -0.53995683,  0.02972014, ...,  0.22950932,
         0.51975176, -0.15294191],
       [ 0.99672772, -1.18005215, -0.20548559, ...,  0.51975176,
         1.53916369,  0.33917967],
       [ 0.53854978,  0.44074198, -0.53622537, ..., -0.15294191,
         0.33917967,  1.39970668]])

In [ ]:
np.cov(m).shape     #10000x10000 need to take transpose of m

(10000, 10000)

In [ ]:
np.cov(m.transpose())   #close to identity

array([[ 0.98417357, -0.00293066,  0.00327935],
       [-0.00293066,  1.01648195, -0.00291989],
       [ 0.00327935, -0.00291989,  1.02473278]])

In [ ]:
np.random.randint(0,10000,(2,3))

array([[8340, 8229,  926],
       [ 285, 1873, 7583]])

In [ ]:
np.random.uniform(0,1,(100,2))

array([[3.92638998e-01, 2.26710236e-01],
       [7.35697181e-01, 8.34906691e-01],
       [1.02361296e-01, 9.15318339e-01],
       [6.10524036e-01, 3.08393801e-01],
       [9.36573043e-01, 6.72720510e-01],
       [7.61514447e-01, 7.55928622e-01],
       [3.48860362e-01, 3.91675524e-01],
       [5.91409702e-03, 1.75350808e-01],
       [5.81210580e-01, 6.49303107e-01],
       [3.80014276e-01, 8.95968788e-01],
       [2.35807475e-01, 3.46949240e-01],
       [7.92646689e-01, 9.72572576e-01],
       [9.56409235e-01, 8.46202225e-01],
       [1.05008777e-02, 3.64840101e-01],
       [5.49634376e-01, 7.88523297e-01],
       [4.96191280e-01, 8.07193730e-01],
       [9.67500537e-01, 8.02393909e-01],
       [6.18069681e-01, 8.81249656e-01],
       [5.00685537e-02, 6.53937184e-01],
       [4.80733800e-01, 9.86357767e-01],
       [2.87405401e-01, 2.36717909e-01],
       [2.64046611e-01, 4.42828538e-01],
       [5.62066651e-01, 1.60596349e-01],
       [1.99532467e-01, 9.29818283e-01],
       [5.326205

In [ ]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
A[A%2==0]

array([0, 2, 4, 6, 8])